POST http://127.0.0.1:8000/persistence/build/postgres
Content-Type: application/json

{
    "dbname": "restapi",
    "user": "luisnquin",
    "password": "UltimateNinja998"
}


// The persistence name would be
// postgres, PostgreSQL, mysql, MySQL